import React from 'react';
import './Footer.css'; // Make sure to create and link the CSS file

const Footer = () => {
    return (
        <footer className="footer">
            <div className="footer-content">
                <p>fff</p>
                <p>Follow us on social media!</p>
                {/* Add social media links/icons here */}
            </div>
        </footer>
    );
};

export default Footer;